package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        powerShell {
            name = "Copy Sencha framework"
            minRequiredVersion = "7"
            formatStderrAsError = true
            scriptMode = script {
                content = """Expand-Archive -Path C:\Assets\ExtJS\ext-7.0.0.zip -DestinationPath .\"""
            }
        }
        powerShell {
            name = "Rename framework folder"
            minRequiredVersion = "7"
            formatStderrAsError = true
            scriptMode = script {
                content = """Rename-Item .\ext-7.0.0.156 ext"""
            }
        }
        powerShell {
            name = "Sencha production build"
            minRequiredVersion = "7"
            formatStderrAsError = true
            scriptMode = script {
                content = "sencha app build production"
            }
        }
        powerShell {
            name = "Zip production build"
            minRequiredVersion = "7"
            formatStderrAsError = true
            workingDir = """.\build\production\MyApp"""
            scriptMode = script {
                content = """Compress-Archive -Path .\ -DestinationPath ..\CustomersMapApp.zip"""
            }
        }
    }
    steps {
        update<PowerShellStep>(1) {
            name = "Rename Ext JS framework folder"
            clearConditions()
        }
    }
}
